[package]
name = "hyperbench"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.87"
nix = { version = "0.29.0", features = ["time"] }
os_pipe = "1.2.1"
sha-crypt = "0.5.0"
socketpair = "0.19.5"
